"""empty message

Revision ID: a697330510c2
Revises: 14f22e94e7a9
Create Date: 2023-07-13 18:15:10.372789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a697330510c2'
down_revision = '14f22e94e7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('showtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('seat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ticket_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_pkey')
    )
    # ### end Alembic commands ###
